<?php
namespace app\components;
/**
 * Created by PhpStorm.
 * User: user
 * Date: 03.10.2018
 * Time: 13:52
 */
use Yii;
use yii\web\Controller;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(\Yii::$app->user->isGuest)
        {
            $this->redirect('/site/login');
        }
    }

    public function actionSetsearch()
    {
        $session = Yii::$app->session;
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if(Yii::$app->request->post()['searchset'])
        {
            $searchset = Yii::$app->request->post()['searchset'];
            //$searchset[] = $searchset['value'];
            //$val = array();
            //$val = ;
            if($session->has('searchs'))
            {
                $sess = $session->get('searchs');
                $sess[ $searchset['url']] =$searchset['value'];
                $session->set('searchs' , $sess);
            }
            else
            {
                $session->set('searchs' ,[ $searchset['url'] =>$searchset['value']]);

            }
            //    $sess = $session['searchs']['urls']
            //    $session->set('searchs' ,['urls' => $val]);
            return 'recordSaved';
        }
    }

    public function actionGetsearch()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $session = Yii::$app->session;
        if(Yii::$app->request->post()['url'])
        {
            $url = Yii::$app->request->post()['url'];
            if($session->has('searchs')&&isset($session['searchs'][$url]))
            {
                return $session['searchs'][$url];
            }else
            {
                return 'not';
            }
        }
    }

    public function actionGetyear()
    {
        $session = Yii::$app->session;

        if($session->has('current_year')&&isset($session['current_year']))
        {
            return $session['current_year'];
        }else {
            $session['current_year'] = date("Y");
            return $session['current_year'];
        }

    }
    public function actionSetyear()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if(Yii::$app->request->post()['current_year'])
        {
            $curYear = Yii::$app->request->post()['current_year'];
            $session = Yii::$app->session;
            $session['current_year']  = $curYear;

            return 'year saved';

        }
    }



}